# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.rpc import code_pb2 as google_dot_rpc_dot_code__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x07\x65xample\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/rpc/code.proto\"!\n\x0cHelloRequest\x12\x11\n\tyour_name\x18\x01 \x01(\t\"@\n\rHelloResponse\x12\x1e\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x10.google.rpc.Code\x12\x0f\n\x07message\x18\x02 \x01(\t2\\\n\x0cHelloService\x12L\n\x08SayHello\x12\x15.example.HelloRequest\x1a\x16.example.HelloResponse\"\x11\x82\xd3\xe4\x93\x02\x0b\"\x06/hello:\x01*B8\n\x16org.example.grpc.protoB\nHelloProtoZ\x12\x65xample/grpc/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026org.example.grpc.protoB\nHelloProtoZ\022example/grpc/proto'
  _globals['_HELLOSERVICE'].methods_by_name['SayHello']._loaded_options = None
  _globals['_HELLOSERVICE'].methods_by_name['SayHello']._serialized_options = b'\202\323\344\223\002\013\"\006/hello:\001*'
  _globals['_HELLOREQUEST']._serialized_start=77
  _globals['_HELLOREQUEST']._serialized_end=110
  _globals['_HELLORESPONSE']._serialized_start=112
  _globals['_HELLORESPONSE']._serialized_end=176
  _globals['_HELLOSERVICE']._serialized_start=178
  _globals['_HELLOSERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
